support content-range header
dart-lang/shelf_static pull request #59
Opened 2021-06-12 02:32 UTC by Nightmare-MY

i don't know some code like matches[1]! whether  call on a null

2021-06-12 02:35 UTC, Nightmare-MY commented
@googlebot I signed it!

2021-06-12 02:39 UTC, kevmoo commented
Please add tests!

2021-06-12 03:04 UTC, Nightmare-MY commented
> 请添加测试！

I added

2021-06-12 16:06 UTC, kevmoo requested changes
This is a great start, but we need to do more.

Need to reply with the 'Accept-Ranges: bytes' for all file requests.

See more here https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests

2021-06-16 01:31 UTC, Nightmare-MY commented
> This is a great start, but we need to do more.
> 
> Need to reply with the 'Accept-Ranges: bytes' for all file requests.
> 
> See more here https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests

i added,is that so?

2021-06-16 23:40 UTC, kevmoo commented
I think we need a LOT more testing here. What are we supported to do with invalid ranges, etc.

CC @natebosch

2021-06-17 06:35 UTC, Nightmare-MY commented
> I think we need a LOT more testing here. What are we supported to do with invalid ranges, etc.
> 
> CC @natebosch

now i added.

2021-06-20 09:29 UTC, Nightmare-MY commented
now i added more test,Is that right?

2021-07-02 03:13 UTC, Nightmare-MY commented
hello,Is there anything I haven't done yet? @kevmoo

2021-07-02 13:43 UTC, kevmoo commented
Thoughts @natebosch ?

2021-07-02 20:48 UTC, natebosch commented on lib/src/static_handler.dart
> +        if (request.method == 'HEAD') {
https://datatracker.ietf.org/doc/html/rfc7233#section-3.1

> A server MUST ignore a Range header field received with a request method other than GET.

2021-07-02 21:06 UTC, kevmoo approved these changes

2021-07-02 21:06 UTC, kevmoo commented
I'm going to land as-is and do a follow-up. Thanks @Nightmare-MY !!

2021-07-02 21:07 UTC, merged

2021-07-02 21:27 UTC, kevmoo commented on lib/src/static_handler.dart
> +        if (request.method == 'HEAD') {
I just tried this w/ https://storage.googleapis.com/dart-archive/channels/stable/release/2.13.4/sdk/dartsdk-macos-x64-release.zip.sha256sum

And it IS honored for HEAD responses. Returned with a `content-length` of `5`

2021-07-02 22:37 UTC, natebosch commented on lib/src/static_handler.dart
> +        if (request.method == 'HEAD') {
I cannot repro.

```
curl --head https://storage.googleapis.com/dart-archive/channels/stable/release/2.13.4/sdk/dartsdk-macos-x64-release.zip.sha256sum -H "Range: 0-5" | grep content-length

x-goog-stored-content-length: 96
content-length: 96
```

2021-07-02 23:08 UTC, kevmoo commented on lib/src/static_handler.dart
> +        if (request.method == 'HEAD') {
```
curl --head https://storage.googleapis.com/dart-archive/channels/stable/release/2.13.4/sdk/dartsdk-macos-x64-release.zip.sha256sum -H "Range: bytes=0-5" | grep content-length

x-goog-stored-content-length: 96
content-length: 6
```

2021-07-02 23:08 UTC, kevmoo commented on lib/src/static_handler.dart
> +        if (request.method == 'HEAD') {
must specify `bytes=0-5`

2021-07-02 23:21 UTC, natebosch commented on lib/src/static_handler.dart
> +        if (request.method == 'HEAD') {
😳 Ah yeah I did miss the `bytes=`...

This is a hard call to make. The spec is unambiguous, but it does look like buggy servers are fairly common and from a little searching it seems some clients depend on those bugs 😞 

@jakemac53 - WDYT?

2021-07-02 23:26 UTC, kevmoo commented on lib/src/static_handler.dart
> +        if (request.method == 'HEAD') {
For comparison: https://raw.githubusercontent.com/dart-lang/shelf_static/range_side_by_side/example/files/dart_sdk_test_example.sha256sum

2021-07-09 19:08 UTC, kevmoo commented
This is published now as v1.1 @Nightmare-MY

2021-07-13 02:32 UTC, Nightmare-MY commented
thanks! @kevmoo